using Application.Interfaces.Messaging;
using Application.SupplyAndProductionManagement.SupplyChainManagement.Shared;

namespace Application.SupplyAndProductionManagement.SupplyChainManagement.TransactionalPartnerAggregate.Queries.GetSuppliers;

public sealed record GetSuppliersQuery : IQuery<IReadOnlyList<SuppliersResponse>>;
