using Application.Interfaces.Messaging;

namespace Application.SupplyAndProductionManagement.SupplyChainManagement.TransactionalPartnerAggregate.Commands.DeleteTransactionalPartner;

public sealed record DeleteTransactionalPartnerCommand(Guid Id) : ICommand;